image: node:latest

cache:
    paths:
        - node_modules/

pages:
  script:
  - npm install -g @angular/cli
  - npm install
  - npm run build
  - mv dist/qr-generator public
  artifacts:
    paths:
    - public
  only:
  - master
